Repository UQdeco2800/2021-studio-2, pull requests merged in 2021-09, with the labels that each got.

#161 Team 3 - Javadocs and TestFiles
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/crate/CrateAnimationController.java
  source/core/src/main/com/deco2800/game/components/crate/TransformBarrelComponent.java
  source/core/src/main/com/deco2800/game/components/crate/TransformEntityComponent.java
  source/core/src/main/com/deco2800/game/components/tasks/ShootProjectileTask.java
  source/core/src/main/com/deco2800/game/components/tasks/ZigChaseTask.java
  source/core/src/main/com/deco2800/game/entities/factories/CutsceneTriggerFactory.java
  source/core/src/main/com/deco2800/game/ui/textbox/TextBoxInputComponent.java
  source/core/src/test/com/deco2800/game/components/CombatStatsComponentTest.java
  source/core/src/test/com/deco2800/game/components/TouchHealComponentTest.java
  source/core/src/test/com/deco2800/game/components/crate/CrateAnimationControllerTest.java
  source/core/src/test/com/deco2800/game/components/crate/TransformBarrelComponentTest.java
Labels: documentation, Team 3, refactor

#162 Team 1.3
  source/core/src/main/com/deco2800/game/entities/factories/CutsceneTriggerFactory.java
  source/core/src/main/com/deco2800/game/files/PlayerSave.java
  source/core/src/main/com/deco2800/game/ui/textbox/TextBox.java
Labels: Team 1

#163 Changed the button to correctly start the tutorial game.
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
Labels: Team 1

#164 Team 3
  source/core/assets/crate/crateHitBreak.png
Labels: Team 3, art asset
