Repository UQdeco2800/2021-studio-2, pull requests merged in 2021-08, with the labels that each got.

#56 Merge branch 2.1 into branch 2 - issue #43 Projectile movement and rotation
  source/core/assets/configs/arrow.json
  source/core/assets/images/arrow.atlas
  source/core/assets/images/arrow.png
  source/core/assets/images/arrow1.png
  source/core/assets/images/arrow2.png
  source/core/assets/images/arrow3.png
  source/core/assets/images/arrow4.png
  source/core/assets/images/test.atlas
  source/core/assets/test/files/test.atlas
  source/core/src/main/com/deco2800/game/ai/tasks/AITaskComponent.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/npc/ArrowAnimationController.java
  source/core/src/main/com/deco2800/game/components/tasks/AttackTask.java
  source/core/src/main/com/deco2800/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/deco2800/game/entities/factories/ArrowFactory.java
  source/core/src/main/com/deco2800/game/utils/math/Vector2Utils.java
  source/desktop/build.gradle
Labels: feature, combat, Sprint 1, Team 2, task ticket

#64 Team 3 - Low Health UI + heart beat sound, Death Screen, Main Menu
  source/core/assets/images/Valhalla_title.png
  source/core/assets/images/main_menu_background.png
  source/core/assets/lowHealthImages/testBlood1.png
  source/core/assets/lowHealthImages/testBlood2.png
  source/core/assets/lowHealthImages/testDeath1.png
  source/core/assets/lowHealthImages/youdied.png
  source/core/assets/mainMenuSkin/mainMenu.atlas
  source/core/assets/mainMenuSkin/mainMenu.json
  source/core/assets/mainMenuSkin/mainMenu.png
  source/core/assets/mainMenuSkin/pixel.fnt
  source/core/assets/sounds/heartBeat_placeholder.wav
  source/core/src/main/com/deco2800/game/GdxGame.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/death/DeathActions.java
  source/core/src/main/com/deco2800/game/components/death/DeathDisplay.java
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/components/player/PlayerLowHealthDisplay.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/deco2800/game/screens/DeathScreen.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/screens/MainMenuScreen.java
Labels: feature

#80 Team 3 - updated main menu bg and buttons, bloodied view and heart beat sound
  source/core/assets/configs/player.json
  source/core/assets/images/main_menu_background.png
  source/core/assets/lowHealthImages/BloodScreenDarkRepositioned.png
  source/core/assets/mainMenuSkin/mainMenu.atlas
  source/core/assets/mainMenuSkin/mainMenu.json
  source/core/assets/mainMenuSkin/mainMenu.png
  source/core/assets/sounds/heartBeat_placeholder.mp3
  source/core/src/main/com/deco2800/game/components/mainmenu/MainMenuDisplay.java
  source/core/src/main/com/deco2800/game/components/player/PlayerLowHealthDisplay.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
Labels: Sprint 1, Team 3, refactor, tidy up
